apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product-service 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: venkat8430/product-service:38
        ports:
        - containerPort: 8080
